# Generated by Django 3.2.9 on 2021-11-10 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='full_url',
            new_name='long_url',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='url_hash',
            new_name='short_url',
        ),
    ]
